openapi: 3.0.0
info:
  description: DEMO Backend API
  version: 1.0.0
  title: DEMO Backend API

tags:
  - name: Name
    description: Demo application

paths:
  /demo/api/v1/cities:
    get:
      tags:
        - City
      operationId: findAllCities
      summary: show a list of all cities
      description: returns all the cities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/City'
        '204':
          description: No content
  /demo/api/v1/employees:
    get:
      tags:
        - Steden
      operationId: findAllSteden
      summary: show a list of all steden
      description: returns all the steden
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stad'
        '204':
          description: No content
  /demo/api/v1/employees:
    get:
      tags:
        - Employee
      operationId: findAllEmployees
      summary: show a list of all employees
      description: returns all the employees
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
        '204':
          description: No content
  /demo/api/v1/employees:
    get:
      tags:
        - Employee
      operationId: findAllEmployees
      summary: show a list of all employees
      description: returns all the employees
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
        '204':
          description: No content
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The id of the Employee
        firstName:
          type: string
          description: first name of the Employee
        lastName:
          type: string
          description: last name of the Employee
        emailId:
          type: string
          description: email address
    City:
      type: object
      properties:
#        id:
#          type: integer
#          format: int64
#          description: The id of the City
        name:
          type: string
          description: name of the City
        population:
          type: integer
          format: int64
          description: number of inhabtants of the City